### ISSUE TITLE
Version requirements

### ISSUE THREAD

**Issue by pianonyy** [maxwells-daemons/accompany-music-vae#1]
Hello, Aidan!

Please, could you tell me, which versions of Tensorflow and Keras did you use?

**Comment by maxwells-daemons** [comment]
Sorry, I don't recall the exact versions. Your main constraint will be compatibility with [Magenta's MusicVAE](https://github.com/magenta/magenta/tree/main/magenta/models/music_vae), so I'd suggest first trying to get that running, and then any compatible version of TF/keras ought to work from there.

**Comment by smcio** [comment]
hey @pianonyy - did you by any chance manage to solve your problem and figure out compatible package versions needed to run the project? I'm suffering from all sorts of Dependency / Version Hell in trying to get a Magenta environment working, so it'd be much appreciated if you could share the wisdom if you happen to have figured it out already! :)

**Comment by pianonyy** [comment]
@smcio  Yes. tf == 1.15, magenta == 1.2.1

**Comment by smcio** [comment]
@pianonyy Thanks very much indeed. Would you mind also sharing what version of Python worked for the combination of this project with those dependencies? Thanks again.

**Comment by pianonyy** [comment]
@smcio Python3.7
